import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";

// Import the separate client component:


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <AuthProvider>
        <body
          className={`
            ${geistSans.variable} 
            ${geistMono.variable} 
            antialiased 
            bg-gray-100 
            dark:bg-gray-900 
            text-gray-900 
            dark:text-gray-100 
            transition-colors 
            duration-300
          `}
        >
          {/* 🔥 Insert the client-side toggle button here */}
          
          <Navbar />
          {children}
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}